spring:
  application:
    name: price-service
  h2:
    console:
      path: /h2-console
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:price
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 9020
